[build]
  publish = "/public"

[build.environment]
  HUGO_VERSION = "0.66.0"
  HUGO_BUILDFUTURE = "true"

[context.deploy-preview.environment]
  command = "hugo -d public --baseURL $DEPLOY_PRIME_URL"

