[build]
publish = "/public"
command = "hugo -d public"
HUGO_VERSION = "0.72.0"

[context.branch-deploy]
command = "hugo --gc -b $DEPLOY_PRIME_URL"

[context.deploy-preview]
command = "hugo --gc -b $DEPLOY_PRIME_URL
